# Generated by Django 2.0.5 on 2021-06-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0004_auto_20210611_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='NseCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strikePrice', models.IntegerField()),
                ('expiryDate', models.CharField(max_length=20)),
                ('underlying', models.CharField(max_length=20)),
                ('identifier', models.CharField(max_length=20)),
                ('openInterest', models.IntegerField()),
                ('changeinOpenInterest', models.IntegerField()),
                ('pchangeinOpenInterest', models.FloatField()),
                ('totalTradedVolume', models.IntegerField()),
                ('impliedVolatility', models.FloatField()),
                ('lastPrice', models.FloatField()),
                ('change', models.FloatField()),
                ('pChange', models.FloatField()),
                ('totalBuyQuantity', models.IntegerField()),
                ('totalSellQuantity', models.IntegerField()),
                ('bidQty', models.IntegerField()),
                ('bidprice', models.FloatField()),
                ('askQty', models.IntegerField()),
                ('askPrice', models.FloatField()),
                ('underlyingValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NsePE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strikePrice', models.IntegerField()),
                ('expiryDate', models.CharField(max_length=20)),
                ('underlying', models.CharField(max_length=20)),
                ('identifier', models.CharField(max_length=20)),
                ('openInterest', models.IntegerField()),
                ('changeinOpenInterest', models.IntegerField()),
                ('pchangeinOpenInterest', models.FloatField()),
                ('totalTradedVolume', models.IntegerField()),
                ('impliedVolatility', models.FloatField()),
                ('lastPrice', models.FloatField()),
                ('change', models.FloatField()),
                ('pChange', models.FloatField()),
                ('totalBuyQuantity', models.IntegerField()),
                ('totalSellQuantity', models.IntegerField()),
                ('bidQty', models.IntegerField()),
                ('bidprice', models.FloatField()),
                ('askQty', models.IntegerField()),
                ('askPrice', models.FloatField()),
                ('underlyingValue', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Nse',
        ),
    ]
