from django.db import models

# Create your models here.
class NseCE(models.Model):
    strikePrice = models.IntegerField()
    expiryDate = models.CharField(max_length=20)
    underlying = models.CharField(max_length=20)
    identifier = models.CharField(max_length=20)
    openInterest =  models.IntegerField()
    changeinOpenInterest =  models.IntegerField()
    pchangeinOpenInterest = models.FloatField()
    totalTradedVolume = models.IntegerField()
    impliedVolatility = models.FloatField()
    lastPrice = models.FloatField()
    change = models.FloatField()
    pChange = models.FloatField()
    totalBuyQuantity = models.IntegerField()
    totalSellQuantity = models.IntegerField()
    bidQty = models.IntegerField()
    bidprice = models.FloatField()
    askQty = models.IntegerField()
    askPrice = models.FloatField()
    underlyingValue = models.FloatField()

class NsePE(models.Model):
    strikePrice = models.IntegerField()
    expiryDate = models.CharField(max_length=20)
    underlying = models.CharField(max_length=20)
    identifier = models.CharField(max_length=20)
    openInterest =  models.IntegerField()
    changeinOpenInterest =  models.IntegerField()
    pchangeinOpenInterest = models.FloatField()
    totalTradedVolume = models.IntegerField()
    impliedVolatility = models.FloatField()
    lastPrice = models.FloatField()
    change = models.FloatField()
    pChange = models.FloatField()
    totalBuyQuantity = models.IntegerField()
    totalSellQuantity = models.IntegerField()
    bidQty = models.IntegerField()
    bidprice = models.FloatField()
    askQty = models.IntegerField()
    askPrice = models.FloatField()
    underlyingValue = models.FloatField()
